name: rooya_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  get: ^4.3.8
  dio: ^4.0.0
  http: ^0.13.3
  pin_code_fields: ^7.3.0
  libphonenumber: ^2.0.2
  equatable: ^2.0.3
  timeago: ^3.1.0
  cached_network_image: ^3.1.0
  flutter_tagging: ^3.0.0
  image_picker: ^0.8.4+2
  shared_preferences: ^2.0.8
  google_static_maps_controller: ^0.6.0
  carousel_slider: ^4.0.0
  mime: ^1.0.0
  percent_indicator: ^3.0.1
  flutter_spinkit: ^5.1.0
  persistent_bottom_nav_bar: ^4.0.2
  circular_profile_avatar: ^2.0.5
  shimmer: ^2.0.0
  story_view: ^0.13.1
  storage_path: ^0.2.0
  video_thumbnail:
  permission_handler: ^8.2.5
  file_picker: ^4.1.5
  camera: ^0.9.2+2
  visibility_detector: ^0.2.2
  video_player: ^2.2.5
  get_storage: ^2.0.3
  country_code_picker: ^2.0.2
  flutter_svg: ^0.23.0+1
  image_cropper: ^1.4.1
  photofilters: ^3.0.1
  path: ^1.8.0
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  google_maps_place_picker: ^2.1.0-nullsafety.3
  google_maps_flutter: ^2.0.6
  geolocator: ^7.7.1
  photo_view: ^0.13.0
  reorderables: ^0.4.1
  path_provider: ^2.0.7
  share: ^2.0.4
  url_launcher: ^6.0.13
  crop: ^0.5.1+1
  stickereditor: ^0.0.8
  image_gallery_saver: ^1.7.1
  uri_to_file: ^0.2.0
  mvc_pattern: 8.1.1
  wakelock: ^0.5.6
  video_editor: ^1.2.2
  helpers: ^1.1.4
  socket_io_client: ^1.0.2
  socket_io: ^1.0.1
  better_player: ^0.0.81
  just_audio: ^0.9.18
  rxdart: ^0.27.3
  audio_video_progress_bar: ^0.10.0
  record: ^3.0.2
  open_file: ^3.2.1
  record_mp3: ^3.0.0
  swipe_to: ^0.1.0-nullsafety.1
  flutter_slidable: any
  modal_bottom_sheet: ^2.0.0
  photo_manager: ^2.0.0
  flutter_painter: ^1.0.0
  phosphor_flutter: ^1.4.0
  #video_trimmer: ^1.0.0
  image_cropping: ^0.0.11
  crop_your_image: ^0.6.0+1



  global_configuration: ^2.0.0-nullsafety.1
  convex_bottom_bar: ^3.0.0
  assets_audio_player: 3.0.3+6
  like_button: ^2.0.3
  awesome_dialog: ^2.1.1
  flutter_facebook_auth: 3.5.6
  sign_in_with_apple: 3.2.0
  google_sign_in: ^5.2.0
  sliding_up_panel: ^2.0.0+1
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  device_info: ^2.0.0
  skeleton_loader: ^2.0.0+4
  flutter_native_timezone: 1.0.10
  change_app_package_name: ^1.0.0
  grouped_list: ^4.1.0
  fluttertoast: ^8.0.8
  flutter_xlider: 3.4.0
  flutter_circular_slider: 2.5.0
  flutter_cache_manager: ^3.0.1
  dotted_border: ^2.0.0
  dropdown_search: ^2.0.0
  velocity_x: ^3.0.0
  flutter_phoenix: ^1.0.0
  liquid_progress_indicator_ns: 1.0.0
  google_mobile_ads: ^0.12.1+1
  uni_links: ^0.5.1
  flutter_local_notifications: 5.0.0+4
  platform_device_id: 1.0.1
  firebase_messaging: 11.1.0
  pusher_client:
    path: ./packages_list/pusher_client
  laravel_chat:
    path: ./packages_list/laravel_chat
  emoji_picker_flutter: 1.0.7
  animated_text_kit: 4.2.1
  flutter_swiper_plus: ^2.0.4
  gallery_saver: ^2.3.2
  #flutter_ffmpeg: ^0.4.2
  #ffmpeg_kit_flutter: ^4.5.0
  flutter_staggered_grid_view: ^0.6.0
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/logo.png"
  image_path_android: "assets/logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/flags/
    - assets/socialicons/
    - assets/svg/
    - assets/cfg/
    - assets/reelAssets/fonts/
    - assets/reelAssets/icons/
    - assets/reelAssets/images/
    - assets/reelAssets/pics/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: segmdl2
      fonts:
        - asset: assets/fonts/segmdl2.ttf
    - family: segoepr
      fonts:
        - asset: assets/fonts/segoepr.ttf
    - family: segoeprb
      fonts:
        - asset: assets/fonts/segoeprb.ttf
    - family: segoesc
      fonts:
        - asset: assets/fonts/segoesc.ttf
    - family: segoescb
      fonts:
        - asset: assets/fonts/segoescb.ttf
    - family: segoeui
      fonts:
        - asset: assets/fonts/segoeui.ttf
    - family: segoeuib
      fonts:
        - asset: assets/fonts/segoeuib.ttf
    - family: segoeuii
      fonts:
        - asset: assets/fonts/segoeuii.ttf
    - family: segoeuil
      fonts:
        - asset: assets/fonts/segoeuil.ttf
    - family: segoeuisl
      fonts:
        - asset: assets/fonts/segoeuisl.ttf
    - family: segoeuiz
      fonts:
        - asset: assets/fonts/segoeuiz.ttf
    - family: seguibl
      fonts:
        - asset: assets/fonts/seguibl.ttf
    - family: seguibli
      fonts:
        - asset: assets/fonts/seguibli.ttf
    - family: seguiemj
      fonts:
        - asset: assets/fonts/seguiemj.ttf
    - family: seguihis
      fonts:
        - asset: assets/fonts/seguihis.ttf
    - family: seguili
      fonts:
        - asset: assets/fonts/seguili.ttf
    - family: seguisb
      fonts:
        - asset: assets/fonts/seguisb.ttf
    - family: seguisli
      fonts:
        - asset: assets/fonts/seguisli.ttf
    - family: seguisym
      fonts:
        - asset: assets/fonts/seguisym.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
